## This playbook will setup the dr control instance specified in the hosts_dr_crontrol file w/ necessary script to perform a full DR cutover when executed.
- hosts: drcontrol
  remote_user: ubuntu 
  vars:
    app_user: ubuntu
    app_group: ubuntu
    app_dir: /home/{{ app_user }}/dr_control
    drdb1:
      vol_id: vol-b23bf9a7
      ip: 172.16.98.21
      instance_id: i-98bd3841
      itype: m3.2xlarge
      sg: sg-ba3099de
    drdb2:
      vol_id: vol-618493a1
      ip: 172.16.103.151
      instance_id: i-b97deb61
      itype: m3.2xlarge
      sg: sg-ba3099de
    drweb1:
      itype: t2.large
      instance_id: i-91ce1b58
      ip: 172.16.3.12
      sg: sg-66b21c02
      dashboard_dbhosts:
        citinew-dashboard: drdb2-slave.naehas.net
        comcastprod-dashboard: drdb2-slave.naehas.net
        coxprod-dashboard: drdb2-slave.naehas.net
        dmiplatform-dashboard: drdb1-slave.neahas.net
        pncprod-dashboard: drdb1-slave.naehas.net
        salesdemo-dashboard: drdb1-slave.naehas.net
        statefarm-dashboard: drdb1-slave.naehas.net
        usbankprod-dashboard: drdb2-slave.naehas.net
    aws_region: us-west-2
  tasks:
    - include: "tasks/base.yml"
    - include: "tasks/app.yml"
    - include: "tasks/aws_cli.yml"
    - include: "tasks/ruby_gems.yml"
    - include: "tasks/vol_snapshot.yml"
    - include: "tasks/dr_control_setup.yml"