- hosts: drdb
  remote_user: ubuntu 
  vars:
    app_user: ubuntu
    app_group: ubuntu
    aws_region: us-west-2
  tasks:
    - include: "tasks/aws_cli.yml"
    - include: "tasks/dr_ssh_access.yml"
    - include: "tasks/drdb.yml"