- name: Install software-properties-common
  sudo: yes
  apt: name=software-properties-common state=present

- name: Install build-essential
  sudo: yes
  apt: name=build-essential state=present

- name: Install ruby1.9.1
  sudo: yes
  apt: name=ruby1.9.1 state=present

- name: install unzip
  sudo: yes
  apt: name=unzip state=present